from enum import Enum


class Parser(Enum):
    PRODUCED_INFER_PARSER = 'PRODUCED_INFER_PARSER'
    PRODUCED_STRING_PARSER = 'PRODUCED_STRING_PARSER'
    REQUIRED_SPARK_EXECUTION_PARSER = 'PRODUCED_SPARK_EXECUTION_PARSER'
    REQUIRED_STRING_PARSER = 'REQUIRED_STRING_PARSER'